# Generated by Django 5.1 on 2024-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_folderconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderConfig',
        ),
    ]
