# Generated by Django 5.1 on 2024-08-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
